### PR TITLE
Ada Lovelace

### PR DESCRIPTION
**Pull request by wirelessben**
Add Ada Lovelace's program for calculating Bernoulli Numbers using Charles Babbage's Analytical Engine. It's open source, critical, and feminist because Ada published her program in 1843, one hundred years before Alan Turing created the computer that broke Enigma. Her algorithm is in Note G of the citation. Her program uses "Variable-cards" and a loop called a "cycle of a cycle of Variable-cards".

### CODE REVIEW

**Comment by juliaferraioli** [comment]
Thanks for opening the first pull request!

I'm struggling with this one honestly. There's no denying the momentous impact that Ada Lovelace had on computer science and computing as a whole, but could you elaborate on its relationship to open source specifically? I'm having a hard time putting it in that context.

(Please note that something can absolutely be of critical impact to technology overall but be less of a critical event for open source. I would anticipate that if we can tie this event back to open source more concretely, I would recommend making this a [`note` to indicate that it is more tangential/commentary](https://github.com/juliaferraioli/opensource-timeline/blob/main/README.md?plain=1#L19).)

**Comment by wirelessben** [comment]
Well, it's source code, and she openly published it, so that fits the definition of open source, per se.

**Comment by wirelessben** [comment]
I originally labeled it critical because she did have impacts beyond the open-source ecosystem, as an example of an accomplished woman 80 years before women got the right to vote and as a brilliant person. I mean, the Analytical Engine only existed on paper, and she wrote a program for it! Computer scientists named a whole computer language after her. The Imitation Game could easily have been made about her.

Anyway, you already know her impact, so I defer to your good judgment.

**Comment by amcasari** [comment]
This has lit up different parts of my brain. Rather than spinning these thoughts internally, hoping to discuss more with you both (all!) here.

1. Could this be argued to be the first open source program ever released? If not in 2022 legal + technical terms, but in the spirit of what open source software is? Maybe we should break down further what should be included as "open source" - definition or intent? Do we get to accredit the work before the movement was defined or named with its modern meanings?

2. Other potential modern labels - "public domain", "free software"

3. What's the criteria we should be using here to measure against what is an open source event? Must it be discretely definable? How broad does the impact have to be and for how long? Good questions for discussion!

**Comment by wirelessben** [comment]
@amcasari Glad you liked the discussion. 

1. Yes. Yes. No. Yes. 
2. Possibly. 
- "Public domain" software is a legal minefield. If you wrote it and someone dies, you could be sued. But sure, it could be a label.
- "Free software" should be defined with the GNU four freedoms: (0) to run the program, (1) to study and change the program in source code form, (2) to redistribute exact copies, and (3) to distribute modified versions.
3. Criteria: Are they instructions for a machine? Can you run, see, modify, and distribute them without being sued? See the 4 freedoms above.

Julia is oversubscribed, so I'm _fine_ with her decision, whatever it is.

**Comment by juliaferraioli** [comment]
While we do deal with legal milestones on this timeline, I don't think that we need to get into the weeds of liability (outside of documented cases that are, themselves, open source events).

I'm thinking there should be a cutoff on timing, but I'll move that discussion to an issue.

I really dislike declining this PR, both as an admirer of Ada Lovelace and as a feminist, but I think this is a bit too far removed from the cultural and technical open source software movement to be included.

I propose closing this PR, but with the understanding that we will reopen it if the scope changes. @wirelessben, does that sound okay to you?

**Comment by wirelessben** [comment]
I'm fine with it, @juliaferraioli. Ada's code was the first event I thought of when you tweeted. If others don't feel the same, then I was just a one off. Thanks for your consideration.

**Pull request closed without merging**
